package keyboardctl

const (
	WH_KEYBOARD_LL = 13
	WM_KEYDOWN     = 0x0100
	WM_SYSKEYDOWN  = 0x0104
	WM_KEYUP       = 0x0101
	WM_SYSKEYUP    = 0x0105
	// VK_SHIFT       = 0xa0
	// VK_CONTROL     = 0xa2
)

// 真正的键盘虚拟码VKCODE
const (
	VK_LBUTTON             = 1  //鼠标左键
	VK_RBUTTON             = 2  //鼠标右键
	VK_CANCEL              = 3  //Cancel
	VK_MBUTTON             = 4  //鼠标中键
	VK_XBUTTON1            = 5  //X1鼠标按钮
	VK_XBUTTON2            = 6  //X2鼠标按钮
	VK_BACK                = 8  //Backspace
	VK_TAB                 = 9  //Tab
	VK_CLEAR               = 12 //Clear
	VK_RETURN              = 13 //Enter
	VK_SHIFT               = 16 //Shift
	VK_CONTROL             = 17 //Ctrl
	VK_ALT                 = 18 //ALt
	VK_PAUSE               = 19 //Pause
	VK_CAPITAL             = 20 //Caps Lock
	VK_KANA                = 21 //IME假名模式
	VK_HANGUL              = 21 //IME Hanguel模式（保持兼容性；使用VK_HANGUL）
	VK_HANGEUL             = 21 //IME韩文模式
	VK_JUNJA               = 23 //IME Junja模式
	VK_FINAL               = 24 //IME最终模式
	VK_HANJA               = 25 //IME Hanja模式
	VK_HANJI               = 25 //IME汉字模式
	VK_ESCAPE              = 27 //Esc
	VK_CONVERT             = 28 //输入法转换
	VK_NONCONVERT          = 29 //IME不可转换
	VK_ACCETP              = 30 //输入法接受
	VK_MODECHANGE          = 31 //输入法模式更改请求
	VK_SPACE               = 32 //Space
	VK_PRIOR               = 33 //Page Up
	VK_NEXT                = 34 //Page Down
	VK_END                 = 35 //End
	VK_HOME                = 36 //Home
	VK_LEFT                = 37 //Left Arrow
	VK_UP                  = 38 //Up Arrow
	VK_RIGHT               = 39 //Right Arrow
	VK_DOWN                = 40 //Down Arrow
	VK_SELECT              = 41 //Select
	VK_PRINT               = 42 //Print
	VK_EXECUTE             = 43 //Execute
	VK_SNAPSHOT            = 44 //Snapshot
	VK_INSERT              = 45 //Insert
	VK_DELETE              = 46 //Delete
	VK_HELP                = 47 //Help
	VK_0                   = 48
	VK_1                   = 49
	VK_2                   = 50
	VK_3                   = 51
	VK_4                   = 52
	VK_5                   = 53
	VK_6                   = 54
	VK_7                   = 55
	VK_8                   = 56
	VK_9                   = 57
	VK_A                   = 65
	VK_B                   = 66
	VK_C                   = 67
	VK_D                   = 68
	VK_E                   = 69
	VK_F                   = 70
	VK_G                   = 71
	VK_H                   = 72
	VK_I                   = 73
	VK_J                   = 74
	VK_K                   = 75
	VK_L                   = 76
	VK_M                   = 77
	VK_N                   = 78
	VK_O                   = 79
	VK_P                   = 80
	VK_Q                   = 81
	VK_R                   = 82
	VK_S                   = 83
	VK_T                   = 84
	VK_U                   = 85
	VK_V                   = 86
	VK_W                   = 87
	VK_X                   = 88
	VK_Y                   = 89
	VK_Z                   = 90
	VK_LWIN                = 91  //左Windows键（自然键盘）
	VK_RWIN                = 92  //右Windows键（自然键盘）
	VK_APPS                = 93  //应用程序键（自然键盘）
	VK_SLEEP               = 95  //电脑睡眠键
	VK_NUMPAD0             = 96  //小键盘0
	VK_NUMPAD1             = 97  //小键盘1
	VK_NUMPAD2             = 98  //小键盘2
	VK_NUMPAD3             = 99  //小键盘3
	VK_NUMPAD4             = 100 //小键盘4
	VK_NUMPAD5             = 101 //小键盘5
	VK_NUMPAD6             = 102 //小键盘6
	VK_NUMPAD7             = 103 //小键盘7
	VK_NUMPAD8             = 104 //小键盘8
	VK_NUMPAD9             = 105 //小键盘9
	VK_MULTIPLY            = 106 //小键盘 *
	VK_ADD                 = 107 //小键盘 +
	VK_SEPARATOR           = 108 //小键盘 Enter
	VK_SUBTRACT            = 109 //小键盘 -
	VK_DECIMAL             = 110 //小键盘 .
	VK_DIVIDE              = 111 //小键盘 /
	VK_F1                  = 112 //F1
	VK_F2                  = 113 //F2
	VK_F3                  = 114 //F3
	VK_F4                  = 115 //F4
	VK_F5                  = 116 //F5
	VK_F6                  = 117 //F6
	VK_F7                  = 118 //F7
	VK_F8                  = 119 //F8
	VK_F9                  = 120 //F9
	VK_F10                 = 121 //F10
	VK_F11                 = 122 //F11
	VK_F12                 = 123 //F12
	VK_F13                 = 124
	VK_F14                 = 125
	VK_F15                 = 126
	VK_F16                 = 127
	VK_F17                 = 128
	VK_F18                 = 129
	VK_F19                 = 130
	VK_F20                 = 131
	VK_F21                 = 132
	VK_F22                 = 133
	VK_F23                 = 134
	VK_F24                 = 135
	VK_MUMLOCK             = 144 //Num Lock
	VK_SCROLL              = 145 //Scroll
	VK_LSHIFT              = 160 //左SHIFT键
	VK_RSHIFT              = 161 //右SHIFT键
	VK_LCONTROL            = 162 //左CONTROL键
	VK_RCONTROL            = 163 //右CONTROL键
	VK_LALT                = 164 //左ALT键
	VK_RALT                = 165 //右ALT键
	VK_BROWSER_BACK        = 166 //浏览器后退键
	VK_BROWSER_FORWARD     = 167 //浏览器前进键
	VK_BROWSER_REFRESH     = 168 //浏览器刷新键
	VK_BROWSER_STOP        = 169 //浏览器停止键
	VK_BROWSER_SEARCH      = 170 //浏览器搜索键
	VK_BROWSER_FAVORITES   = 171 //浏览器收藏夹键
	VK_BROWSER_HOME        = 172 //浏览器开始和主页键
	VK_VOLUME_MUTE         = 173 //音量静音键
	VK_VOLUME_DOWN         = 174 //降低音量键
	VK_VOLUME_UP           = 175 //调高音量键
	VK_MEDIA_NEXT_TRACK    = 176 //下一曲目键
	VK_MEDIA_PREV_TRACK    = 177 //上一曲目键
	VK_MEDIA_STOP          = 178 //停止媒体键
	VK_MEDIA_PLAY_PAUSE    = 179 //播放/暂停媒体键
	VK_LAUNCH_MAIL         = 180 //启动邮件密钥
	VK_LAUNCH_MEDIA_SELECT = 181 //选择媒体密钥
	VK_LAUNCH_APP1         = 182 //启动应用程序1键
	VK_LAUNCH_APP2         = 183 //启动应用程序2键
	VK_OEM_1               = 186 //;
	VK_OEM_PLUS            = 187 //=+
	VK_OEM_COMMA           = 188
	VK_OEM_MINUS           = 189 //-_
	VK_OEM_PERIOD          = 190
	VK_OEM_2               = 191 ///?
	VK_OEM_3               = 192 //`~
	VK_OEM_4               = 219 //[{
	VK_OEM_5               = 220 //\ |
	VK_OEM_6               = 221 //]}
	VK_OEM_7               = 222 //'"
	VK_OEM_8               = 223
	VK_OEM_102             = 226
	VK_ICO_HELP            = 227
	VK_ICO_00              = 228
	VK_PROCESSKEY          = 229
	VK_ICO_CLEAR           = 230
	VK_PACKET              = 231
	VK_OEM_RESET           = 233
	VK_OEM_JUMP            = 234
	VK_OEM_PA1             = 235
	VK_OEM_PA2             = 236
	VK_OEM_PA3             = 237
	VK_OEM_WSCTRL          = 238
	VK_OEM_CUSEL           = 239
	VK_OEM_ATTN            = 240
	VK_OEM_FINISH          = 241
	VK_OEM_COPY            = 242
	VK_OEM_AUTO            = 243
	VK_OEM_ENLW            = 244
	VK_OEM_BACKTAB         = 245
	VK_ATTN                = 246
	VK_CRSEL               = 247
	VK_EXSEL               = 248
	VK_EREOF               = 249
	VK_PLAY                = 250
	VK_ZOOM                = 251
	VK_NONAME              = 252
	VK_PA1                 = 253
	VK_OEM_CLEAR           = 254
)
