// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function Startup(startupstate: boolean): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(434882655, startupstate) as any;
    return $resultPromise;
}

export function StartupState(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3426770320) as any;
    return $resultPromise;
}
