// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @param {boolean} startupstate
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function Startup(startupstate) {
    let $resultPromise = /** @type {any} */($Call.ByID(434882655, startupstate));
    return $resultPromise;
}

/**
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function StartupState() {
    let $resultPromise = /** @type {any} */($Call.ByID(3426770320));
    return $resultPromise;
}
